---
- name: Configure SSH and hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Add hosts to /etc/hosts
      lineinfile:
        path: /etc/hosts 
        regexp: "{{ hostvars[item].ansible_host }}"
        line: "{{ hostvars[item].ansible_host }} {{ item.split('.')[0] }}.example.com {{ item.split('.')[0] }}"
        state: present
      loop: "{{ ansible_play_hosts }}"
      become: true 

